### ISSUE TITLE
Ошибка с логом при завершении бэка

### ISSUE THREAD

**Issue by gsbelarus** [gsbelarus/gdmn#197]
С последними обновлениями системы логирования появились такие сообщения при завершении бэка:
```
log4js.fileAppender - Writing to file logs\all.log, error happened  Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:250:14)
    at RollingFileStream.Writable.write (_stream_writable.js:299:5)
    at RollingFileStream.Writable.end (_stream_writable.js:587:10)
    at Function.app.shutdown (C:\Golden\NS\gdmn\node_modules\log4js\lib\appenders\file.js:67:12)
    at C:\Golden\NS\gdmn\node_modules\log4js\lib\log4js.js:115:59
    at Array.forEach (<anonymous>)
    at Object.shutdown (C:\Golden\NS\gdmn\node_modules\log4js\lib\log4js.js:115:44)
    at C:\Golden\NS\gdmn\src\gdmn-back\dist\src\index.js:81:61
    at new Promise (<anonymous>)
    at logShutdown (C:\Golden\NS\gdmn\src\gdmn-back\dist\src\index.js:81:11)
    at process.exit (C:\Golden\NS\gdmn\src\gdmn-back\dist\src\index.js:52:19)
```

Надо разобраться. Похоже на некорректное завершение лога. Что-то подобное описано тут:

https://github.com/log4js-node/log4js-node/issues/374

**Comment by IharOknorp** [comment]
установил версию node 12.10.0
```
[2019-09-10T12:15:24.075] [INFO] default - WebSocket server is closed
[2019-09-10T12:15:24.076] [INFO] default - Http server is closed
[2019-09-10T12:15:24.077] [INFO] database - alias#auth_db (localhost:3050/C:\project\gdmn\src\gdmn-back\databases\MAIN.FDB) is changed; Status: DISCONNECTING; Time: 58309 ms
[2019-09-10T12:15:24.080] [INFO] database - alias#auth_db (C:\project\gdmn\src\gdmn-back\databases\MAIN.FDB) closed all sessions
[2019-09-10T12:15:24.088] [INFO] database - alias#auth_db (localhost:3050/C:\project\gdmn\src\gdmn-back\databases\MAIN.FDB) is changed; Status: IDLE; Time: 10 ms
[2019-09-10T12:15:24.093] [INFO] default - StompManager is destroyed
[2019-09-10T12:15:24.094] [INFO] default - Shutdown...

Process finished with exit code 1

```
Делаю ctrl + c - закрывается корректно. Может еще какие то шаги нужно воспроизвести?

**Comment by gsbelarus** [comment]
Опять вылезло. Не надо ничего устанавливать. Хороше же видно в каких строчках ошибка. Разобраться почему к этому моменту уже нет лога, а идет попытка в него писать:
```
log4js.fileAppender - Writing to file logs\errors.log, error happened  Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:250:14)
    at RollingFileStream.Writable.write (_stream_writable.js:299:5)
    at RollingFileStream.Writable.end (_stream_writable.js:587:10)
    at Function.app.shutdown (C:\Golden\NS\gdmn\node_modules\log4js\lib\appenders\file.js:67:12)
    at C:\Golden\NS\gdmn\node_modules\log4js\lib\log4js.js:115:59
    at Array.forEach (<anonymous>)
    at Object.shutdown (C:\Golden\NS\gdmn\node_modules\log4js\lib\log4js.js:115:44)
    at C:\Golden\NS\gdmn\src\gdmn-back\dist\src\index.js:81:61
    at new Promise (<anonymous>)
    at logShutdown (C:\Golden\NS\gdmn\src\gdmn-back\dist\src\index.js:81:11)
    at process.exit (C:\Golden\NS\gdmn\src\gdmn-back\dist\src\index.js:52:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
log4js.fileAppender - Writing to file logs\warns.log, error happened  Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at writeAfterEnd (_stream_writable.js:250:14)
    at RollingFileStream.Writable.write (_stream_writable.js:299:5)
    at RollingFileStream.Writable.end (_stream_writable.js:587:10)
    at Function.app.shutdown (C:\Golden\NS\gdmn\node_modules\log4js\lib\appenders\file.js:67:12)
    at C:\Golden\NS\gdmn\node_modules\log4js\lib\log4js.js:115:59
    at Array.forEach (<anonymous>)
    at Object.shutdown (C:\Golden\NS\gdmn\node_modules\log4js\lib\log4js.js:115:44)
    at C:\Golden\NS\gdmn\src\gdmn-back\dist\src\index.js:81:61
    at new Promise (<anonymous>)
    at logShutdown (C:\Golden\NS\gdmn\src\gdmn-back\dist\src\index.js:81:11)
    at process.exit (C:\Golden\NS\gdmn\src\gdmn-back\dist\src\index.js:52:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
